# Generated by Django 3.2 on 2021-04-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='desctiption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default=-1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.PositiveIntegerField(default=-1),
            preserve_default=False,
        ),
    ]
