# Generated by Django 3.2 on 2021-04-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_promo',
            field=models.BooleanField(default=False),
        ),
    ]
